version: "3.8"

services:
#  api-service:
#    build:
#      context: .
#      network: host
#    restart: always
#    ports:
#      - 8080:8080
#    networks:
#      service-network:
#    depends_on:
#      - db
#      - pgadmin
#    environment:
#        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/order-db
#        - SPRING_DATASOURCE_USERNAME=admin
#        - SPRING_DATASOURCE_PASSWORD=admin
#        - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    build:
      context: .
      network: host
    image: postgres:13.1-alpine
    container_name: postgre-sql
    restart: always
    environment:
      POSTGRES_DB: order-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/db/data
    volumes:
      - db-data:/var/lib/db/data
    ports:
      - 5010:5432

  pgadmin:
    image: dpage/pgadmin4:4.18
    container_name: PgAdmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 5011:80
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - db:db-server

volumes:
  db-data:
  pgadmin-data:
networks:
  service-network:
